export default {
    pk: '',
    sk: '',
    type: '',
    title: '',
    subtitle: '',
    accent_color: '',
    logo: '',
    background_image: '',
    description: '',
    social_links: {
        facebook: '',
        youtube: '',
        twitter: '',
        instagram: '',
        website: '',
    },
    phone: '',
    address: '',
    business_hours: {
        monday: '',
        tuesday: '',
        wednesday: '',
        thursday: '',
        friday: '',
        saturday: '',
        sunday: '',
    },
    email: '',
    ad_image: '',
    promo_video_url: '',
}
